vars:
  - experiment_name: semantic_one
  - dataset:
      root_dir: data/tiered_imagenet
      specs_folder: specs
      distances_folder: distances
      models_folder: models
      metrics_folder: metrics
      tb_logs_folder: tb_logs
  - alpha_grid:
      - 0.005
      - 0.01
      - 0.05
      - 0.1

stages:
  compute_distances:
    foreach:
      - train
      - test
    do:
      cmd: python -m src.compute_semantic_distances
        --split ${item}
        --specs-dir ${dataset.root_dir}/${dataset.specs_folder}
        --output-dir ${dataset.root_dir}/${dataset.distances_folder}
        &> ${dataset.root_dir}/logs/compute_${item}_distances.out
      deps:
        - ${dataset.root_dir}/${dataset.specs_folder}/${item}.json
        - ${dataset.root_dir}/${dataset.specs_folder}/wordnet.is_a.txt
        - src/compute_semantic_distances.py
      outs:
        - ${dataset.root_dir}/logs/compute_${item}_distances.out
        - ${dataset.root_dir}/${dataset.distances_folder}/${item}.csv

  train:
    foreach: ${alpha_grid}
    do:
      cmd: python -m src.train
        --specs-dir ${dataset.root_dir}/${dataset.specs_folder}
        --distances-dir ${dataset.root_dir}/${dataset.distances_folder}
        --metrics-dir ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}
        --tb-log-dir ${dataset.root_dir}/${dataset.tb_logs_folder}/semantic/${item}
        --output-model ${dataset.root_dir}/${dataset.models_folder}/trained_model_semantic_${item}.tar
        --sampler semantic
        --semantic-alpha ${item}
        --device cuda:0
        &> ${dataset.root_dir}/logs/train_semantic_${item}.out
      deps:
        - ${dataset.root_dir}/${dataset.specs_folder}/train.json
        - ${dataset.root_dir}/${dataset.specs_folder}/val.json
        - ${dataset.root_dir}/${dataset.distances_folder}/train.csv
        - src/train.py
      outs:
        - ${dataset.root_dir}/${dataset.models_folder}/trained_model_semantic_${item}.tar
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/training_tasks.pkl
        - ${dataset.root_dir}/logs/train_semantic_${item}.out

  evaluate:
    foreach: ${alpha_grid}
    do:
      cmd: python -m src.evaluate
        --specs-dir ${dataset.root_dir}/${dataset.specs_folder}
        --trained-model ${dataset.root_dir}/${dataset.models_folder}/trained_model_semantic_${item}.tar
        --output-dir ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}
        &> ${dataset.root_dir}/logs/evaluate_${item}.out
      deps:
        - ${dataset.root_dir}/${dataset.models_folder}/trained_model_semantic_${item}.tar
        - ${dataset.root_dir}/${dataset.specs_folder}/test.json
        - src/evaluate.py
      outs:
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/raw_results.csv
        - ${dataset.root_dir}/logs/evaluate_${item}.out

  compute_metrics:
    foreach: ${alpha_grid}
    do:
      cmd: python -m src.compute_metrics
        --distances-dir ${dataset.root_dir}/${dataset.distances_folder}
        --metrics-dir ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}
        &> ${dataset.root_dir}/logs/compute_metrics_${item}.out
      deps:
        - ${dataset.root_dir}/${dataset.distances_folder}/test.csv
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/raw_results.csv
        - src/compute_metrics.py
      outs:
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/task_performances.csv
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/accuracy_v_task_class_distance.png
        - ${dataset.root_dir}/logs/compute_metrics_${item}.out

  get_train_stats:
    foreach: ${alpha_grid}
    do:
      cmd: python -m src.get_training_tasks_stats
        --training-tasks-record ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/training_tasks.pkl
        --distances-dir ${dataset.root_dir}/${dataset.distances_folder}
        --metrics-dir ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}
      deps:
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/training_tasks.pkl
        - ${dataset.root_dir}/${dataset.distances_folder}/train.csv
      outs:
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/intra_training_task_distances.csv
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/training_classes_sampled_together.png
        - ${dataset.root_dir}/${dataset.metrics_folder}/semantic/${item}/training_classes_biconfusion.png
