stages:
  compute_distances:
    foreach:
      - train
      - test
    do:
      cmd: python -m src.compute_semantic_distances
        --split ${item}
        --specs-dir ${specs_dir}
        --output-dir ${distances_dir}
        &> ${logs_dir}/compute_${item}_distances.out
      deps:
        - ${specs_dir}/${item}.json
        - ${specs_dir}/wordnet.is_a.txt
        - src/compute_semantic_distances.py
      outs:
        - ${logs_dir}/compute_${item}_distances.out
        - ${distances_dir}/${item}.csv

  create_testbed:
    foreach:
      - 1
      - 5
    do:
      cmd: python -m src.create_testbed
        --n-shot ${item}
        --out-file ${testbeds_dir}/testbed_${item}_shot.csv
      deps:
        - ${specs_dir}/test.json
        - ${distances_dir}/test.csv
        - src/create_testbed.py
      outs:
        - ${testbeds_dir}/testbed_${item}_shot.csv
        - ${testbeds_dir}/testbed_${item}_shot_pv.png
        - ${testbeds_dir}/testbed_${item}_shot_occ.png

  train:
    foreach: ${grid_search}
    do:
      cmd: python -m src.train
        --specs-dir ${specs_dir}
        --distances-dir ${distances_dir}
        --metrics-dir ${metrics_dir}/${item.name}
        --tb-log-dir ${tb_logs_dir}/${item.name}
        --output-model ${models_dir}/trained_model_${item.name}.tar
        --sampler ${item.sampler}
        --semantic-alpha ${item.alpha}
        --random-seed 0
        --device cuda:1
        &> ${logs_dir}/train_${item.name}.out
      deps:
        - ${specs_dir}/train.json
        - ${specs_dir}/val.json
        - ${distances_dir}/train.csv
        - src/train.py
      outs:
        - ${models_dir}/trained_model_${item.name}.tar
        - ${metrics_dir}/${item.name}/training_tasks.pkl
        - ${logs_dir}/train_${item.name}.out

  evaluate:
    foreach: ${grid_search}
    do:
      cmd: python -m src.evaluate
        --specs-dir ${specs_dir}
        --testbed ${testbeds_dir}/testbed_5_shot.csv
        --trained-model ${models_dir}/trained_model_${item.name}.tar
        --output-dir ${metrics_dir}/${item.name}
        --device cuda:1
        &> ${logs_dir}/evaluate_${item.name}.out
      deps:
        - ${models_dir}/trained_model_${item.name}.tar
        - ${specs_dir}/test.json
        - ${testbeds_dir}/testbed_5_shot.csv
        - src/evaluate.py
      outs:
        - ${metrics_dir}/${item.name}/raw_results.csv
        - ${logs_dir}/evaluate_${item.name}.out

  compute_metrics:
    foreach: ${grid_search}
    do:
      cmd: python -m src.compute_metrics
        --testbed ${testbeds_dir}/testbed_5_shot.csv
        --metrics-dir ${metrics_dir}/${item.name}
        &> ${logs_dir}/compute_metrics_${item.name}.out
      deps:
        - ${testbeds_dir}/testbed_5_shot.csv
        - ${metrics_dir}/${item.name}/raw_results.csv
        - src/compute_metrics.py
      outs:
        - ${metrics_dir}/${item.name}/accuracy_v_variance.png
        - ${logs_dir}/compute_metrics_${item.name}.out
      metrics:
        - ${metrics_dir}/${item.name}/evaluation_metrics.json
      plots:
        - ${metrics_dir}/${item.name}/task_performances.csv:
            x: variance
            y: accuracy
            title: ${item.name}
            template: smooth

  get_train_stats:
    foreach: ${grid_search}
    do:
      cmd: python -m src.get_training_tasks_stats
        --training-tasks-record ${metrics_dir}/${item.name}/training_tasks.pkl
        --distances-dir ${distances_dir}
        --metrics-dir ${metrics_dir}/${item.name}
      deps:
        - ${metrics_dir}/${item.name}/training_tasks.pkl
        - ${distances_dir}/train.csv
      outs:
        - ${metrics_dir}/${item.name}/intra_training_task_distances.csv
        - ${metrics_dir}/${item.name}/training_classes_sampled_together.png
        - ${metrics_dir}/${item.name}/training_classes_biconfusion.png
