specs_dir: data/tiered_imagenet/specs
distances_dir: data/tiered_imagenet/distances
models_dir: data/tiered_imagenet/models
metrics_dir: data/tiered_imagenet/metrics
tb_logs_dir: data/tiered_imagenet/tb_logs
logs_dir: data/tiered_imagenet/logs
testbeds_dir: data/tiered_imagenet/testbeds

number_of_ways:
  - 1
  - 5

grid_search:
  - sampler: semantic
    alpha: 0.0
    seed: 0
    name: semantic_0_seed_0
  - sampler: semantic
    alpha: 0.001
    seed: 0
    name: semantic_e3_seed_0
  - sampler: semantic
    alpha: 0.01
    seed: 0
    name: semantic_e2_seed_0
  - sampler: semantic
    alpha: 0.1
    seed: 0
    name: semantic_e1_seed_0
  - sampler: uniform
    alpha: 0.0
    seed: 0
    name: uniform_seed_0
  - sampler: adaptive
    alpha: 0.0
    seed: 0
    name: adaptive_seed_0
  - sampler: semantic
    alpha: 0.0
    seed: 1
    name: semantic_0_seed_1
  - sampler: semantic
    alpha: 0.001
    seed: 1
    name: semantic_e3_seed_1
  - sampler: semantic
    alpha: 0.01
    seed: 1
    name: semantic_e2_seed_1
  - sampler: semantic
    alpha: 0.1
    seed: 1
    name: semantic_e1_seed_1
  - sampler: uniform
    alpha: 0.0
    seed: 1
    name: uniform_seed_1
  - sampler: adaptive
    alpha: 0.0
    seed: 1
    name: adaptive_seed_1

device: cuda:1

random_seed: 1